# -*- coding: UTF-8 -*-

import os

if __name__ == '__main__':
    cmds = [
        'git submodule add "https://github.com/rikyoz/bit7z.git" "C-C++/ThirdPartyLibrarys/compression/bit7z"',
        'git submodule add "https://github.com/songwenhao/zlib.git" "C-C++/ThirdPartyLibrarys/compression/zlib"',
        'git submodule add "https://github.com/songwenhao/libzip.git" "C-C++/ThirdPartyLibrarys/compression/libzip"',
        'git submodule add "https://github.com/songwenhao/libimobiledevice-glue.git" "C-C++/ThirdPartyLibrarys/apple/libimobiledevice-glue"',
        'git submodule add "https://github.com/songwenhao/libusbmuxd.git" "C-C++/ThirdPartyLibrarys/apple/libusbmuxd"',
        'git submodule add "https://github.com/songwenhao/libplist.git" "C-C++/ThirdPartyLibrarys/apple/libplist"',
        'git submodule add "https://github.com/songwenhao/libimobiledevice.git" "C-C++/ThirdPartyLibrarys/apple/libimobiledevice"',
        'git submodule add "https://github.com/songwenhao/ideviceinstaller.git" "C-C++/ThirdPartyLibrarys/apple/ideviceinstaller"',
        'git submodule add "https://github.com/zeux/pugixml.git" "C-C++/ThirdPartyLibrarys/xml/pugixml"',
        'git submodule add "https://github.com/leethomason/tinyxml2.git" "C-C++/ThirdPartyLibrarys/xml/tinyxml2"',
        'git submodule add "https://github.com/DaveGamble/cJSON.git" "C-C++/ThirdPartyLibrarys/json/cJSON"',
        'git submodule add "https://github.com/Tencent/rapidjson.git" "C-C++/ThirdPartyLibrarys/json/rapidjson"',
        'git submodule add "https://github.com/nlohmann/json.git" "C-C++/ThirdPartyLibrarys/json/json"',
        'git submodule add "https://github.com/protocolbuffers/protobuf.git" "C-C++/ThirdPartyLibrarys/serialization/protobuf"',
        'git submodule add "https://github.com/Tencent/MMKV.git" "C-C++/ThirdPartyLibrarys/serialization/MMKV"',
        'git submodule add "https://github.com/unicode-org/icu.git" "C-C++/ThirdPartyLibrarys/character-encoding/icu"',
        'git submodule add "https://github.com/songwenhao/libiconv.git" "C-C++/ThirdPartyLibrarys/character-encoding/libiconv"',
        'git submodule add "https://github.com/FFmpeg/FFmpeg.git" "C-C++/ThirdPartyLibrarys/multimedia/FFmpeg"',
        'git submodule add "https://github.com/ImageMagick/ImageMagick.git" "C-C++/ThirdPartyLibrarys/multimedia/ImageMagick"',
        'git submodule add "https://github.com/mackyle/sqlite.git" "C-C++/ThirdPartyLibrarys/database/sqlite"',
        'git submodule add "https://github.com/songwenhao/sqlcipher.git" "C-C++/ThirdPartyLibrarys/database/sqlcipher"',
        'git submodule add "https://github.com/yhirose/cpp-httplib.git" "C-C++/ThirdPartyLibrarys/network/cpp-httplib"',
        'git submodule add "https://github.com/curl/curl.git" "C-C++/ThirdPartyLibrarys/network/curl"',
        'git submodule add "https://github.com/grpc/grpc.git" "C-C++/ThirdPartyLibrarys/network/grpc"',
        'git submodule add "https://github.com/warmcat/libwebsockets.git" "C-C++/ThirdPartyLibrarys/network/libwebsockets"',
        'git submodule add "https://github.com/zaphoyd/websocketpp.git" "C-C++/ThirdPartyLibrarys/network/websocketpp"',
        'git submodule add "https://github.com/uNetworking/uSockets.git" "C-C++/ThirdPartyLibrarys/network/uSockets"',
        'git submodule add "https://github.com/uNetworking/uWebSockets.git" "C-C++/ThirdPartyLibrarys/network/uWebSockets"',
        'git submodule add "https://github.com/ithewei/libhv.git" "C-C++/ThirdPartyLibrarys/network/libhv"',
        'git submodule add "https://github.com/libuv/libuv.git" "C-C++/ThirdPartyLibrarys/network/libuv"',
        'git submodule add "https://github.com/enki/libev.git" "C-C++/ThirdPartyLibrarys/network/libev"',
        'git submodule add "https://github.com/libevent/libevent.git" "C-C++/ThirdPartyLibrarys/network/libevent"',
        'git submodule add "https://github.com/nginx/nginx.git" "C-C++/ThirdPartyLibrarys/network/nginx"',
        'git submodule add "https://github.com/memcached/memcached.git" "C-C++/ThirdPartyLibrarys/network/memcached"',
        'git submodule add "https://github.com/redis/redis.git" "C-C++/ThirdPartyLibrarys/network/redis"',
        'git submodule add "https://github.com/shonm520/mu_event.git" "C-C++/ThirdPartyLibrarys/network/mu_event"',
        'git submodule add "https://github.com/chenshuo/muduo.git" "C-C++/ThirdPartyLibrarys/network/muduo"',
        'git submodule add "https://github.com/pocoproject/poco.git" "C-C++/ThirdPartyLibrarys/network/poco"',
        'git submodule add "https://github.com/scylladb/seastar.git" "C-C++/ThirdPartyLibrarys/network/seastar"',
        'git submodule add "https://github.com/wolfSSL/wolfssl.git" "C-C++/ThirdPartyLibrarys/network/wolfssl"',
        'git submodule add "https://github.com/ARMmbed/mbedtls.git" "C-C++/ThirdPartyLibrarys/network/mbedtls"',
        'git submodule add "https://github.com/libressl-portable/portable.git" "C-C++/ThirdPartyLibrarys/network/libressl"',
        'git submodule add "https://github.com/openssl/openssl.git" "C-C++/ThirdPartyLibrarys/network/openssl"',
        'git submodule add "https://github.com/libssh2/libssh2.git" "C-C++/ThirdPartyLibrarys/network/libssh2"',
        'git submodule add "https://github.com/openssh/openssh-portable.git" "C-C++/ThirdPartyLibrarys/network/openssh"',
        'git submodule add "https://github.com/mkj/dropbear.git" "C-C++/ThirdPartyLibrarys/network/dropbear"',
        'git submodule add "https://github.com/WayneD/rsync.git" "C-C++/ThirdPartyLibrarys/network/rsync"',
        'git submodule add "https://github.com/github/putty.git" "C-C++/ThirdPartyLibrarys/network/putty"',
        'git submodule add "https://github.com/chriskohlhoff/asio.git" "C-C++/ThirdPartyLibrarys/network/asio"',
        'git submodule add "https://github.com/GerHobbelt/pthread-win32.git" "C-C++/ThirdPartyLibrarys/windows/pthread-win32"',
        'git submodule add "https://github.com/PowerShell/openssh-portable.git" "C-C++/ThirdPartyLibrarys/windows/openssh-win32"',
        'git submodule add "https://github.com/ImageMagick/ImageMagick-Windows.git" "C-C++/ThirdPartyLibrarys/windows/ImageMagick-Windows"',
        'git submodule add "https://github.com/stefankueng/grepWin.git" "C-C++/ThirdPartyLibrarys/windows/grepWin"',
        'git submodule add "https://github.com/TortoiseGit/tortoisesvn.git" "C-C++/ThirdPartyLibrarys/windows/tortoisesvn"',
        'git submodule add "https://github.com/TortoiseGit/TortoiseGit.git" "C-C++/ThirdPartyLibrarys/windows/TortoiseGit"',
        'git submodule add "https://github.com/winscp/winscp.git" "C-C++/ThirdPartyLibrarys/windows/winscp"',
        'git submodule add "https://github.com/openssl/openssl.git" "C-C++/ThirdPartyLibrarys/crypto/openssl"',
        'git submodule add "https://github.com/weidai11/cryptopp.git" "C-C++/ThirdPartyLibrarys/crypto/cryptopp"',
        'git submodule add "https://github.com/libtom/libtomcrypt.git" "C-C++/ThirdPartyLibrarys/crypto/libtomcrypt"',
        'git submodule add "https://github.com/randombit/botan.git" "C-C++/ThirdPartyLibrarys/crypto/botan"',
        'git submodule add "https://github.com/gabime/spdlog.git" "C-C++/ThirdPartyLibrarys/tools/spdlog"',
        'git submodule add "https://github.com/google/glog.git" "C-C++/ThirdPartyLibrarys/tools/glog"',
        'git submodule add "https://github.com/log4cplus/log4cplus.git" "C-C++/ThirdPartyLibrarys/tools/log4cplus"',
        'git submodule add "https://github.com/google/googletest.git" "C-C++/ThirdPartyLibrarys/tools/googletest"',
        'git submodule add "https://github.com/troydhanson/uthash.git" "C-C++/ThirdPartyLibrarys/tools/uthash"'
    ]

    for cmd in cmds:
        os.system(cmd)
